### ISSUE TITLE
Allow user-provided Rmd templates

### ISSUE THREAD

**Issue by Pakillo** [EcologyR/labeleR#24]
Related to #23 

We could include another argument to allow the possibility to use a user-provided Rmd template (probably modified from the pkg templates, but not necessarily). 

I think this is important because otherwise the user is forced to use pkg templates "as is", which for many users may be too limiting and will move out of labeleR. If we allow for custom templates, that will suit many more people.

**Comment by iramosgutierrez** [comment]
Yes, this is something we had in our mind, we thik it would be quite useful!
