### ISSUE TITLE
create_badge gives error when affiliation.column not provided

### ISSUE THREAD

**Issue by Pakillo** [EcologyR/labeleR#27]
Should affiliation.column be required? Currently gives error if not provided. 

If we want to make it optional, need to amend the function so as not to attempt selecting that column from data (https://github.com/EcologyR/labeleR/blob/d82e4896bd77414e29556ccba7c00bc9431f7254/R/badge.R#L148)

Reprex:

``` r
library(labeleR)
#> Welcome to the labeleR package! Let's create some labels!
#>  Amazing! This is just like magic! 
#> 
#>  Package developed by Julia G. de Aledo & Ignacio Ramos-Gutiérrez
#>  🐦  TW:  @juliagdealedo 
#>  🐦  TW:  @iramosgutierrez
#> 

data <- read_sheet(url = 'https://docs.google.com/spreadsheets/d
        /16smXdP-Ehwu1cEmJTbJI1DerIpUrOcD7H5Ni6z9B07M/edit#gid=0')
create_badge(
  data = data,
  path = "labeleR_output",
  event = "INTERNATIONAL CONFERENCE OF MUGGLEOLOGY",
  name.column = "List",
  # affiliation.column = "Affiliation",
  lpic = NULL,
  rpic = NULL)
#> The specified folder does not exist. Creating folder
#> Error in `[.data.frame`(data, , affiliation.column): undefined columns selected
```

<sup>Created on 2023-05-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by juliagdealedo** [comment]
i.e.  `render(affiliation.column.i = if((affiliation.column==""   )){bl.char}else{data [,affiliation.column]})`
