### ISSUE TITLE
Multiple certificates per page

### ISSUE THREAD

**Issue by Pakillo** [EcologyR/labeleR#5]
Using pgfpage latex package:
```
---
title: "Untitled"
output: pdf_document
header-includes:
  - \usepackage{pgfpages}
  - \pgfpagesuselayout{4 on 1}[a4paper,border shrink=5mm,landscape]
---
```

Mannual de pgfpages: https://stuff.mit.edu/afs/athena/contrib/tex-contrib/beamer/pgf-1.01/doc/generic/pgf/version-for-tex4ht/en/pgfmanualse16.html

**Comment by iramosgutierrez** [comment]
Solved, finally using params!
