### ISSUE TITLE
Release labeleR 0.1.0

### ISSUE THREAD

**Issue by Pakillo** [EcologyR/labeleR#54]
First release:

* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#sec-code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks> (see https://github.com/JosiahParry/extrachecks)
* [x] `devtools::spell_check()`
* [x] `devtools::run_examples()`
* [x] `devtools::test_coverage()`
* [x] `goodpractice::gp()`
* [x] `rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"))`

Prepare for release:

* [x] `git pull`
* [x] `urlchecker::url_check()`
* [x] `devtools::build_readme()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `devtools::check_mac_release()`
* [x] `devtools::check_rhub()` or `rhub::check_for_cran()`
* [x] update cran_comments
* [x] `git push`

Submit to CRAN:

* [x] `usethis::use_version('minor')`
* [x] `devtools::release()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [ ] Optional: `usethis::use_github_release()`

**Comment by iramosgutierrez** [comment]
Well, as it is finally accepted, I think we can close this issue!
