### ISSUE TITLE
Rename `create_tinylabel`

### ISSUE THREAD

**Issue by Pakillo** [EcologyR/labeleR#57]
For consistency, it should probably be renamed as `create_tiny_label`, like the other functions. Before #54

**Comment by Pakillo** [comment]
Actually some functions are "create_certificate_type" but label functions are "create_collection_label" etc. instead of "create_label_type". Probably not necessary to change at this point, but could be changed for consistency

**Comment by juliagdealedo** [comment]
You are right, all function names should be changed. However, we have encountered some problems by doing so, we have decided to change it afterwards in an other branch and after the cran check.

**Comment by Pakillo** [comment]
Which problems? Let me know if I can help. 
Any function name change should ideally be done before submitting to CRAN, to avoid breaking changes once it's public there

**Comment by iramosgutierrez** [comment]
closed in commit d1ce6cefde0609f0c21f120f0115162f74d3f010
